version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: airflow-postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:
    image: apache/airflow:3.0.6
    container_name: airflow-init
    depends_on:
      - postgres
    env_file:
      - ./airflow/airflow.env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname admin
      --lastname admin
      --role Admin
      --email admin@example.com
      "

  airflow-api-server:
    image: apache/airflow:3.0.6
    container_name: airflow-api-server
    hostname: airflow-api-server
    restart: always
    depends_on:
      - postgres
      - airflow-init
    env_file:
      - ./airflow/airflow.env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    command: api-server
    ports:
      - "8081:8080"

  airflow-scheduler:
    image: apache/airflow:3.0.6
    container_name: airflow-scheduler
    hostname: airflow-scheduler
    restart: always
    depends_on:
      - postgres
      - airflow-init
    env_file:
      - ./airflow/airflow.env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    command: scheduler

  airflow-dag-processor:
    image: apache/airflow:3.0.6
    container_name: airflow-dag-processor
    hostname: airflow-dag-processor
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./airflow/airflow.env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    command: dag-processor

  fastapi-wrapper:
    build: ./fastapi-wrapper
    container_name: fastapi-wrapper
    restart: always
    depends_on:
      - airflow-api-server
    environment:
      AIRFLOW_BASE_URL: http://airflow-api-server:8080
      AIRFLOW_USERNAME: admin
      AIRFLOW_PASSWORD: admin
    ports:
      - "8000:8000"



  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd
    restart: always
    environment:
      ETCD_NAME: etcd
      ETCD_DATA_DIR: /etcd-data
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379






  apisix:
    image: apache/apisix:3.9.1-debian
    container_name: apisix
    restart: always
    depends_on:
      - etcd
      - fastapi-wrapper
    ports:
      - "9080:9080"
      - "9180:9180"
    environment:
      APISIX_STAND_ALONE: "false"
    volumes:
      - ./apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro


